Add controllers
AntonFeklichev/java-shareit pull request #1
Opened 2022-11-04 11:54 UTC by AntonFeklichev

2022-11-10 11:09 UTC, AntonFeklichev commented
Для UserController получилось сделать валидацию при PATCH запросах через @Validated и UserPatchValidator, однако аналогичный споспоб для ItemController не сработал - при любых GET, PATCH запросах к этому контроллеру код ответа - 500, а в консоли никаких сообщений об ошибках. В чем может быть проблема?

2022-11-11 20:28 UTC, sergeymamonov commented
> Для UserController получилось сделать валидацию при PATCH запросах через @Validated и UserPatchValidator, однако аналогичный споспоб для ItemController не сработал - при любых GET, PATCH запросах к этому контроллеру код ответа - 500, а в консоли никаких сообщений об ошибках. В чем может быть проблема?

Раз есть 500 код, значит есть какая-то ошибка. То есть нужно посмотреть логи и найти в логах ошибку.

2022-11-11 21:04 UTC, sergeymamonov requested changes

2022-11-12 19:20 UTC, sergeymamonov commented
> > Для UserController получилось сделать валидацию при PATCH запросах через @Validated и UserPatchValidator, однако аналогичный споспоб для ItemController не сработал - при любых GET, PATCH запросах к этому контроллеру код ответа - 500, а в консоли никаких сообщений об ошибках. В чем может быть проблема?
> 
> Раз есть 500 код, значит есть какая-то ошибка. То есть нужно посмотреть логи и найти в логах ошибку. Либо сразу будет понятно, где ошибка, либо поставить брейкпоинты и посмотреть в дебаге.

Удалось разобраться с ошибкой? Если нет, то пишите в слаке.

2022-11-12 19:21 UTC, sergeymamonov approved these changes

2022-11-12 20:08 UTC, merged