Add bookings
AntonFeklichev/java-shareit pull request #2
Opened 2023-02-22 14:10 UTC by AntonFeklichev

2023-02-28 09:07 UTC, sergeymamonov requested changes

2023-03-02 23:12 UTC, AntonFeklichev commented
Еще почему-то не проходит пайплайн (пишет сделать репозиторий публичным, хотя он и так открыт) 
Вот ссылка c логами: https://github.com/AntonFeklichev/java-shareit/actions/runs/4319003772/jobs/7538012160

2023-03-03 22:17 UTC, sergeymamonov commented
> [ItemServiceImpl.java](/AntonFeklichev/java-shareit/pull/2/files/98ada520e7c348488842e027e7f70df0b9fb2514#diff-5ddf49f5a203e7da0787b779d403bc42baa596331d16517e1bb98281fac3108b)
Можно извлечь из БД нужные нам бронирования, и уже на стороне приложения сделать мапу для каждой вещи Map<Item, List<Booking>>

2023-03-03 22:17 UTC, sergeymamonov approved these changes

2023-03-06 12:48 UTC, merged